name: metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "30 3 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: JP
          config_twemoji: yes
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_notable_filter: stars:>10
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
